### ISSUE TITLE
Is this the new website!

### ISSUE THREAD

**Issue by bjorn-ali-goransson** [Warzone2100/wz2100.net#11]
Hi @past-due , was just lurking around the different repos and am delighted to see so much activity here!

Didn't clone this repo but I see it's a netlify web, I think that's greatly needed!

I believe that WZ gets unnecessarily little attention by the public. The current website isn't very accessible, the forums are a conundrum with mostly old, pinned posts ... the "stop with the silly suggestions" post also puts one off unf.

Sure some zealots will be attracted to the game community but I believe that's one burden we will have to bear if we are to make this happen.

**Comment by past-due** [comment]
@bjorn-ali-goransson: This indeed a draft of a new website, built from scratch, using Hugo. Working on getting things translated and fixed-up.

I don't want to post the current temporary link publicly, because we don't want search engines / bots crawling the temporary URL, but if you [join the official Discord](https://discordapp.com/invite/ZvRVQ8g) I'll get you set up with a link to beta-test it.
